export const ELEMENT_NODE = 1 as const;

export const DOCUMENT_POSITION = {
  DISCONNECTED: 1,
  PRECEDING: 2,
  FOLLOWING: 4,
  CONTAINS: 8,
  CONTAINED_BY: 16,
  IMPLEMENTATION_SPECIFIC: 32,
} as const;

export const EVENT_NAME_MAPPING = {
  blur: "onBlur",
  change: "onChange",
  click: "onClick",
  contextmenu: "onContextMenu",
  copy: "onCopy",
  cut: "onCut",
  doubleclick: "onDoubleClick",
  drag: "onDrag",
  dragend: "onDragEnd",
  dragenter: "onDragEnter",
  dragexit: "onDragExit",
  dragleave: "onDragLeave",
  dragover: "onDragOver",
  dragstart: "onDragStart",
  drop: "onDrop",
  error: "onError",
  focus: "onFocus",
  input: "onInput",
  keydown: "onKeyDown",
  keypress: "onKeyPress",
  keyup: "onKeyUp",
  load: "onLoad",
  mousedown: "onMouseDown",
  mouseenter: "onMouseEnter",
  mouseleave: "onMouseLeave",
  mousemove: "onMouseMove",
  mouseout: "onMouseOut",
  mouseover: "onMouseOver",
  mouseup: "onMouseUp",
  paste: "onPaste",
  scroll: "onScroll",
  submit: "onSubmit",
  touchcancel: "onTouchCancel",
  touchend: "onTouchEnd",
  touchmove: "onTouchMove",
  touchstart: "onTouchStart",
  wheel: "onWheel",
} as const;
